config/routes.rb
Cifrao::Application.routes.draw do
  resources :receita

  get "welcome/index"

  resources :despesas

  resources :conta

  resources :entidades

  get "sessions/new"

  get "sessions/destroy"

  get "users/new"

  get "users/reset_password"

  resources :users
  resources :sessions

  match 'sessions/index' => 'sessions#new'

  root :to => 'welcome#index'

end

app/models/despesa.rb
class Despesa < ActiveRecord::Base
  belongs_to :conta_origem
  belongs_to :conta_destino
  attr_accessible :descricao, :valor, :conta_origem_id, :conta_destino_id

  after_create{ |despesa|
    conta = Contum.find(despesa.conta_origem_id)
    conta.saldo = conta.saldo - despesa.valor
    conta.save
  }

  before_update { |despesa|
    conta = Contum.find(despesa.conta_origem_id)
		despesa_antiga = Despesa.find(despesa.id)
		conta.saldo = conta.saldo + despesa_antiga.valor
		conta.save	
   }

   after_update { |despesa|
    conta = Contum.find(despesa.conta_origem_id)
		conta.saldo = conta.saldo - despesa.valor
		conta.save	
   }

   before_destroy { |despesa|
    conta = Contum.find(despesa.conta_origem_id)
		conta.saldo = conta.saldo + despesa.valor
		conta.save	
   }
end

app/controllers/despesas_controller.rb
class DespesasController < ApplicationController
  # GET /despesas
  # GET /despesas.json
  def index
    @despesas = Despesa.all
    @contum = Contum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @despesas }
    end
  end

  # GET /despesas/1
  # GET /despesas/1.json
  def show
    @despesa = Despesa.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @despesa }
    end
  end

  # GET /despesas/new
  # GET /despesas/new.json
  def new
    @despesa = Despesa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @despesa }
    end
  end

  # GET /despesas/1/edit
  def edit
    @despesa = Despesa.find(params[:id])
  end

  # POST /despesas
  # POST /despesas.json
  def create
    @despesa = Despesa.new(params[:despesa])

    respond_to do |format|
      if @despesa.save
        format.html { redirect_to @despesa, notice: 'Despesa was successfully created.' }
        format.json { render json: @despesa, status: :created, location: @despesa }
      else
        format.html { render action: "new" }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /despesas/1
  # PUT /despesas/1.json
  def update
    @despesa = Despesa.find(params[:id])

    respond_to do |format|
      if @despesa.update_attributes(params[:despesa])
        format.html { redirect_to @despesa, notice: 'Despesa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /despesas/1
  # DELETE /despesas/1.json
  def destroy
    @despesa = Despesa.find(params[:id])
    @despesa.destroy

    respond_to do |format|
      format.html { redirect_to despesas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/views/despesas/_form.html.erb
<%= form_for(@despesa) do |f| %>
  <% if @despesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@despesa.errors.count, "error") %> prohibited this despesa from being saved:</h2>

      <ul>
      <% @despesa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :conta_origem %><br />
    <%= f.select :conta_origem_id, Contum.all.collect{|c| [c.nro_conta.to_s + " - " + c.alias.to_s, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :conta_destino %><br />
    <%= f.select :conta_destino_id, Contum.all.collect{|c| [c.nro_conta.to_s + " - " + c.alias.to_s, c.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/despesas/edit.html.erb
<h1>Editing despesa</h1>

<%= render 'form' %>

<%= link_to 'Show', @despesa %> |
<%= link_to 'Back', despesas_path %>

app/views/despesas/index.html.erb
<h1>Listing despesas</h1>

<table>
  <tr>
    <th>Valor</th>
    <th>Descricao</th>
    <th>Conta origem</th>
    <th>Conta destino</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @despesas.each do |despesa| %>
  <tr>
    <td><%= despesa.valor %></td>
    <td><%= despesa.descricao %></td>
    <td><%= Contum.find(despesa.conta_origem_id).agencia %>
        <%= Contum.find(despesa.conta_origem_id).nro_conta %></td>
    <td><%= Contum.find(despesa.conta_destino_id).agencia %>
        <%= Contum.find(despesa.conta_destino_id).nro_conta %></td>
    <td><%= link_to 'Show', despesa %></td>
    <td><%= link_to 'Edit', edit_despesa_path(despesa) %></td>
    <td><%= link_to 'Destroy', despesa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  <tr>
    <td>Total:</td>
    <td><%= @despesas.sum(&:valor) %></td>		
  </tr>
</table>

<br />

<%= link_to 'New Despesa', new_despesa_path %>

app/views/despesas/new.html.erb
<h1>New despesa</h1>

<%= render 'form' %>

<%= link_to 'Back', despesas_path %>

app/views/despesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Valor:</b>
  <%= @despesa.valor %>
</p>

<p>
  <b>Descricao:</b>
  <%= @despesa.descricao %>
</p>

<p>
  <b>Conta origem:</b>
  <%= Contum.find(@despesa.conta_origem_id).agencia %>
  <%= Contum.find(@despesa.conta_origem_id).nro_conta %>
</p>

<p>
  <b>Conta destino:</b>
  <%= Contum.find(@despesa.conta_destino_id).agencia %>
  <%= Contum.find(@despesa.conta_destino_id).nro_conta %>
</p>


<%= link_to 'Edit', edit_despesa_path(@despesa) %> |
<%= link_to 'Back', despesas_path %>