config/routes.rb
Cifrao::Application.routes.draw do
  resources :receita

  get "welcome/index"

  resources :despesas

  resources :conta

  resources :entidades

  get "sessions/new"

  get "sessions/destroy"

  get "users/new"

  get "users/reset_password"

  resources :users
  resources :sessions

  match 'sessions/index' => 'sessions#new'

  root :to => 'welcome#index'

end

app/models/entidade.rb
class Entidade < ActiveRecord::Base
  attr_accessible :cnpj_cpf, :nome
  has_many :contums, foreign_key: "entidades_id", :dependent => :destroy
  validates_presence_of :nome
    validates_length_of :nome, :minimum => 3
end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController
  # GET /entidades
  # GET /entidades.json
  def index
    @entidades = Entidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entidades }
    end
  end

  # GET /entidades/1
  # GET /entidades/1.json
  def show
    @entidade = Entidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entidade }
    end
  end

  # GET /entidades/new
  # GET /entidades/new.json
  def new
    @entidade = Entidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entidade }
    end
  end

  # GET /entidades/1/edit
  def edit
    @entidade = Entidade.find(params[:id])
  end

  # POST /entidades
  # POST /entidades.json
  def create
    @entidade = Entidade.new(params[:entidade])

    respond_to do |format|
      if @entidade.save
        format.html { redirect_to @entidade, notice: 'Entidade was successfully created.' }
        format.json { render json: @entidade, status: :created, location: @entidade }
      else
        format.html { render action: "new" }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entidades/1
  # PUT /entidades/1.json
  def update
    @entidade = Entidade.find(params[:id])

    respond_to do |format|
      if @entidade.update_attributes(params[:entidade])
        format.html { redirect_to @entidade, notice: 'Entidade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entidades/1
  # DELETE /entidades/1.json
  def destroy
    @entidade = Entidade.find(params[:id])
    @entidade.destroy

    respond_to do |format|
      format.html { redirect_to entidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/views/entidades/_form.html.erb
<%= form_for(@entidade) do |f| %>
  <% if @entidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entidade.errors.count, "error") %> prohibited this entidade from being saved:</h2>

      <ul>
      <% @entidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnpj_cpf %><br />
    <%= f.text_field :cnpj_cpf %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entidades/edit.html.erb
<h1>Editing entidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @entidade %> |
<%= link_to 'Back', entidades_path %>

app/views/entidades/index.html.erb
<h1>Listing entidades</h1>

<table>
  <tr>
    <th>Cnpj cpf</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entidades.each do |entidade| %>
  <tr>
    <td><%= entidade.cnpj_cpf %></td>
    <td><%= entidade.nome %></td>
    <td><%= link_to 'Show', entidade %></td>
    <td><%= link_to 'Edit', edit_entidade_path(entidade) %></td>
    <td><%= link_to 'Destroy', entidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entidade', new_entidade_path %>

app/views/entidades/new.html.erb
<h1>New entidade</h1>

<%= render 'form' %>

<%= link_to 'Back', entidades_path %>

app/views/entidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cnpj cpf:</b>
  <%= @entidade.cnpj_cpf %>
</p>

<p>
  <b>Nome:</b>
  <%= @entidade.nome %>
</p>


<%= link_to 'Edit', edit_entidade_path(@entidade) %> |
<%= link_to 'Back', entidades_path %>