config/routes.rb
Cifrao::Application.routes.draw do
  resources :receita

  get "welcome/index"

  resources :despesas

  resources :conta

  resources :entidades

  get "sessions/new"

  get "sessions/destroy"

  get "users/new"

  get "users/reset_password"

  resources :users
  resources :sessions

  match 'sessions/index' => 'sessions#new'

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cifrão $$ Gerencie suas finanças $$</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="apple-touch-icon" href="apple-touch-icon-72x72.png">
  <!-- For iPhone 4 Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
  <!-- For iPad: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
  <link rel="icon" type="image/png" href="favicon.png" />
  <link rel="shortcut icon" href="favicon.ico">
</head>
<body>


<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="<%=root_url%>" class="brand armata"><img src="<%=root_url%>icons/Icone-Cifrao-b32.png" /> Cifrão</a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <% if current_user.nil? %>
          <li><%= link_to "Cadastre-se", new_user_path %></li>
          <li><%= link_to "Entrar", new_session_path %></li>
          <% else %>
          <li class="dropdown closed">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Movimentações <b class="caret"></b></a>			
			<ul class="dropdown-menu">
				<li><%= link_to "Receitas", receita_path %></li>
	            <li><%= link_to "Despesas", despesas_path %></li>
			</ul>
		  </li> 
		  <li class="dropdown closed">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastro <b class="caret"></b></a>			
			<ul class="dropdown-menu">
				<li><%= link_to "Contas", conta_path %></li>
	            <li><%= link_to "Entidades", entidades_path %></li>
			</ul>
		  </li> 
          <li><%= link_to "Preferências" %></li>
          <li><%=link_to "Sair", destroy_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row-fluid">
    <div class="span12">
      <%= yield %>
    </div>
  </div>

</div>
</body>
</html>